formats: 
  - jpg
  - jpeg
  - png
positive_prompt: 
  -Sandra Oh body
  -Kim Kardashian body
  -rihanna
  -taylor swift
negative_prompt: 
  -monochrome, lowres, bad anatomy, worst quality, low quality, cartoon, unrealistic
seed:
  -2
  -4
controlnet_model:
  -
  -